version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "/src/node_modules"
          key: "node_modules"
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node_modules"

      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node_modules"
      - run: npm audit

  build:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node_modules"

      - run: npm i
      - run: npm run build

          
  
workflows:
  integrate:
    jobs:
      - lint
      - test:
          requires:
            - "lint"
      - analyze:
          requires:
            - "test"
      - build:
          requires:
            - "analyze"



